version: '3'
# This Docker Compose file defines three services: Django application, Redis server, and Redis Web Client.
# Django is set to run the development server on port 8000 and connects to Redis for caching/session data.
# Redis is exposed on the default port 6379.
# Redis Web Client (Redis Commander) provides a web interface to manage Redis, accessible on port 8081.

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-web-client:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis