version: '3'

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-web-client:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis